#!/bin/sh /etc/rc.common
START=99
STOP=10

USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /usr/sbin/tailscaled \
        --state=/var/lib/tailscale/tailscaled.state \
        --socket=/var/run/tailscale.sock
    procd_set_param respawn
    procd_close_instance
}

stop_service() {
    killall tailscaled 2>/dev/null || true
}
